#############################################################################
# Makefile for building: UnMineMe.app/Contents/MacOS/UnMineMe
# Generated by qmake (2.01a) (Qt 4.7.4) on: lun. déc. 12 23:38:13 2011
# Project:  UnMineMe.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile UnMineMe.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.7.4/mkspecs/macx-g++ -I. -I/usr/local/Cellar/qt/4.7.4/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.7.4/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.7.4/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.7.4/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.7.4/include -I. -Iheaders -I. -F/usr/local/Cellar/qt/4.7.4/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.7.4/lib -L/usr/local/Cellar/qt/4.7.4/lib -framework QtGui -L/usr/X11/lib -L/usr/local/Cellar/qt/4.7.4/lib -F/usr/local/Cellar/qt/4.7.4/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sources/functions.cpp \
		sources/main.cpp \
		sources/myboard.cpp \
		sources/mysquare.cpp \
		sources/mywindow.cpp moc_myboard.cpp \
		moc_mysquare.cpp \
		moc_mywindow.cpp
OBJECTS       = functions.o \
		main.o \
		myboard.o \
		mysquare.o \
		mywindow.o \
		moc_myboard.o \
		moc_mysquare.o \
		moc_mywindow.o
DIST          = /usr/local/Cellar/qt/4.7.4/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/common/mac-g++.conf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/include_source_dir.prf \
		UnMineMe.pro
QMAKE_TARGET  = UnMineMe
DESTDIR       = 
TARGET        = UnMineMe.app/Contents/MacOS/UnMineMe

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile UnMineMe.app/Contents/PkgInfo UnMineMe.app/Contents/Resources/empty.lproj UnMineMe.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) UnMineMe.app/Contents/MacOS/ || $(MKDIR) UnMineMe.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: UnMineMe.pro  /usr/local/Cellar/qt/4.7.4/mkspecs/macx-g++/qmake.conf /usr/local/Cellar/qt/4.7.4/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/common/mac-g++.conf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.7.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.7.4/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.7.4/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile UnMineMe.pro
/usr/local/Cellar/qt/4.7.4/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.7.4/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.7.4/mkspecs/common/mac-g++.conf:
/usr/local/Cellar/qt/4.7.4/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.7.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.7.4/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.7.4/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.7.4/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile UnMineMe.pro

UnMineMe.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) UnMineMe.app/Contents || $(MKDIR) UnMineMe.app/Contents 
	@$(DEL_FILE) UnMineMe.app/Contents/PkgInfo
	@echo "APPL????" >UnMineMe.app/Contents/PkgInfo
UnMineMe.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) UnMineMe.app/Contents/Resources || $(MKDIR) UnMineMe.app/Contents/Resources 
	@touch UnMineMe.app/Contents/Resources/empty.lproj
	
UnMineMe.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) UnMineMe.app/Contents || $(MKDIR) UnMineMe.app/Contents 
	@$(DEL_FILE) UnMineMe.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,UnMineMe,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.7.4/mkspecs/macx-g++/Info.plist.app >UnMineMe.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/UnMineMe1.0.0 || $(MKDIR) .tmp/UnMineMe1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/UnMineMe1.0.0/ && $(COPY_FILE) --parents headers/functions.h headers/myboard.h headers/mysquare.h headers/mywindow.h .tmp/UnMineMe1.0.0/ && $(COPY_FILE) --parents sources/functions.cpp sources/main.cpp sources/myboard.cpp sources/mysquare.cpp sources/mywindow.cpp .tmp/UnMineMe1.0.0/ && (cd `dirname .tmp/UnMineMe1.0.0` && $(TAR) UnMineMe1.0.0.tar UnMineMe1.0.0 && $(COMPRESS) UnMineMe1.0.0.tar) && $(MOVE) `dirname .tmp/UnMineMe1.0.0`/UnMineMe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/UnMineMe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r UnMineMe.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_myboard.cpp moc_mysquare.cpp moc_mywindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_myboard.cpp moc_mysquare.cpp moc_mywindow.cpp
moc_myboard.cpp: headers/mysquare.h \
		headers/myboard.h
	/usr/local/Cellar/qt/4.7.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ headers/myboard.h -o moc_myboard.cpp

moc_mysquare.cpp: headers/mysquare.h
	/usr/local/Cellar/qt/4.7.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ headers/mysquare.h -o moc_mysquare.cpp

moc_mywindow.cpp: headers/myboard.h \
		headers/mysquare.h \
		headers/functions.h \
		headers/mywindow.h
	/usr/local/Cellar/qt/4.7.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ headers/mywindow.h -o moc_mywindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

functions.o: sources/functions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o sources/functions.cpp

main.o: sources/main.cpp headers/myboard.h \
		headers/mysquare.h \
		headers/functions.h \
		headers/mywindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o sources/main.cpp

myboard.o: sources/myboard.cpp headers/myboard.h \
		headers/mysquare.h \
		headers/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myboard.o sources/myboard.cpp

mysquare.o: sources/mysquare.cpp headers/mysquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysquare.o sources/mysquare.cpp

mywindow.o: sources/mywindow.cpp headers/mywindow.h \
		headers/myboard.h \
		headers/mysquare.h \
		headers/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywindow.o sources/mywindow.cpp

moc_myboard.o: moc_myboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myboard.o moc_myboard.cpp

moc_mysquare.o: moc_mysquare.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mysquare.o moc_mysquare.cpp

moc_mywindow.o: moc_mywindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywindow.o moc_mywindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

